//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace change_masterPage_dynamically {
    
    
    public partial class WebForm1 {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new change_masterPage_dynamically.BaseMaster Master {
            get {
                return ((change_masterPage_dynamically.BaseMaster)(base.Master));
            }
        }
    }
}
